### ISSUE TITLE
AssertionError: Stripped name didn't match author name

### ISSUE THREAD

**Issue by jkotlinski** [csaftoiu/yahoo-groups-backup#37]
```
Failed to process message:
{'authorName': 'Martin Ahnelöv',
 'canDelete': False,
 'contentTrasformed': False,
 'from': 'Martin =?ISO-8859-1?Q?Ahnel=F6v?= &lt;operagasten@...&gt;',
 'headers': {'inReplyToHeader': 'PGRkOTQ0NTEwMDkwODE5MjM0M2w1Y2UxZDk0YnZjY2M0N2RiZGQwNjg5ZWE2QG1haWwuZ21haWwuY29tPg==',
             'messageIdInHeader': 'PDEyNTA3NTA5MzkuNDAzMS4wLmNhbWVsQG1hcnRpbi1kZXNrdG9wPg==',
             'referencesHeader': 'PGUxYzM3MWYwOTA4MTcwMzUxeDYwNTFlNDhmbTEzNTE0NGY0MGNiZWIxZTlAbWFpbC5nbWFpbC5jb20+CSA8aDZjbmJtK3NrMGtAZUdyb3Vwcy5jb20+CSA8ZTFjMzcxZjA5MDgxODAwNTNqNWFmYmJiNzV1NGU1Y2UxYmI2ZmJjMzQ0Y0BtYWlsLmdtYWlsLmNvbT4JIDw0QThCMTdBNS43MDgwNzA5QHNpZHN5bi5jb20+IDwwMDFiMDFjYTIxMTAkZDE2YTdhMTAkNzQzZjZlMzAkQGNvbT4JIDw3MDA5NzdlMTA5MDgxOTE4NDdqNDIzNTczYjVvNmIxZWZmZGE0MTU0OGE0N0BtYWlsLmdtYWlsLmNvbT4JIDxkZDk0NDUxMDA5MDgxOTIzNDNsNWNlMWQ5NGJ2Y2NjNDdkYmRkMDY4OWVhNkBtYWlsLmdtYWlsLmNvbT4='},
 'messageBody': '<div id="ygrps-yiv-341451479">it&#39;s not new, it&#39;s in '
                'the demo version even! =)<br/>\n'
                '<br/>\n'
                'tor 2009-08-20 klockan 02:43 -0400 skrev DDP DDP:<br/>\n'
                '<blockquote><span title="qreply"> &gt; one feature i just '
                'discovered, not sure if this is new, is the tempo TAP<br/>\n'
                '&gt; function in the tempo setting.  If you tap B while the '
                'tempo is selected, it<br/>\n'
                '&gt; sets the tempo to the tempo you are tapping.  Is that '
                'new?  it screwed me up<br/>\n'
                '&gt; a lot while i was setting the tempo.  I would set it to '
                'say, 130, then i<br/>\n'
                '&gt; would listen for a bit, click B again to change it '
                'again, and instead of<br/>\n'
                '&gt; going up to 131, it would go to 40, becasue of the time '
                'between taps.<br/>\n'
                '&gt; <br/>\n'
                '&gt; i guess its something new to get used to.<br/>\n'
                '&gt; <br/>\n'
                '&gt; but i think i&#39;m gonna go back to 3.9.9<br/>\n'
                '&gt; <br/>\n'
                '&gt; <br/>\n'
                '&gt; <br/>\n'
                '&gt; On Wed, Aug 19, 2009 at 9:47 PM, Brady Leo &lt;<a '
                'rel="nofollow" target="_blank" '
                'href="mailto:bradyleo@...">bradyleo@...</a>&gt; wrote:<br/>\n'
                '&gt; <br/>\n'
                '&gt; &gt;<br/>\n'
                '&gt; &gt;<br/>\n'
                '&gt; &gt; Ahhh. This would explain the tremendous trouble I '
                'was having with the WAV<br/>\n'
                '&gt; &gt; channel using keyboard sync mode in the latest '
                'version. I also went back to<br/>\n'
                '&gt; &gt; 3.9.9 and everything worked fine.<br/>\n'
                '&gt; &gt;<br/>\n'
                '&gt; &gt; On Wed, Aug 19, 2009 at 5:05 PM, David '
                'Dineen-Porter &lt;<a rel="nofollow" target="_blank" '
                'href="mailto:theddp@...">theddp@...</a>&lt;theddp%40gmail.com&gt;<br/>\n'
                '&gt; &gt; &gt;wrote:<br/>\n'
                '&gt; &gt;<br/>\n'
                '&gt; &gt;<br/>\n'
                '&gt; &gt; &gt; I think I&#39;m uising 3.9.c. whatever the '
                'latest one is, I forget.<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt; But there&#39;s a bug<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt; If you input a note without instrument number, '
                'at least in the wave<br/>\n'
                '&gt; &gt; &gt; channel,<br/>\n'
                '&gt; &gt; &gt; where I&#39;ve done this, it doesn&#39;t play '
                'the note at that pitch.<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt; Example<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt; C-5 13 -<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt; -- -- P01<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt; E-5 -- --<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt; The note should bend up, and then play at '
                'pitch E-5. Instead, the bend<br/>\n'
                '&gt; &gt; &gt; stops, but the pitch E-5 is not played. '
                'Resulting in a flat note. This<br/>\n'
                '&gt; &gt; &gt; can<br/>\n'
                '&gt; &gt; &gt; be cured by adding the instrument number, '
                'however, this retriggers notw<br/>\n'
                '&gt; &gt; &gt; completely, causing the automated table to '
                'advance one step, and the<br/>\n'
                '&gt; &gt; &gt; envelope to retrigger, causing a slight '
                'click.<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt; This wasn&#39;t the case in 3.9.9, the last '
                'LSDJ I was using.<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt; Just a note.<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt; [Non-text portions of this message have been '
                'removed]<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt; ------------------------------------<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt; Yahoo! Groups Links<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt; &gt;<br/>\n'
                '&gt; &gt;<br/>\n'
                '&gt; &gt; --<br/>\n'
                '&gt; &gt; <a rel="nofollow" target="_blank" '
                'href="http://www.dummydrome.com">http://www.dummydrome.com</a><br/>\n'
                '&gt; &gt;<br/>\n'
                '&gt; &gt; '
                'o----^v--------^v--------^v--------^v--------^v-----------------------------&gt;<br/>\n'
                '&gt; &gt; &quot;If you will it, it is no dream.&quot;<br/>\n'
                '&gt; &gt; -Theodor Herzl<br/>\n'
                '&gt; &gt;<br/>\n'
                '&gt; &gt; [Non-text portions of this message have been '
                'removed]<br/>\n'
                '&gt; &gt;<br/>\n'
                '&gt; &gt;  <br/>\n'
                '&gt; &gt;<br/>\n'
                '&gt; <br/>\n'
                '&gt; <br/>\n'
                '&gt; [Non-text portions of this message have been '
                'removed]<br/>\n'
                '&gt; <br/>\n'
                '&gt; <br/>\n'
                '&gt; <br/>\n'
                '&gt; ------------------------------------<br/>\n'
                '&gt; <br/>\n'
                '&gt; Yahoo! Groups Links<br/>\n'
                '&gt; <br/>\n'
                '&gt; <br/>\n'
                '&gt; </span></blockquote></div>',
 'msgId': 10825,
 'msgSnippet': 'it s not new, it s in the demo version even! =)',
 'nextInTime': 10826,
 'nextInTopic': 10826,
 'numMessagesInTopic': 15,
 'postDate': 1250750939,
 'prevInTime': 10824,
 'prevInTopic': 10824,
 'profile': 'operagasten',
 'rawEmail': 'Return-Path: &lt;operagasten@...&gt;\r\n'
             'X-Sender: operagasten@...\r\n'
             'X-Apparently-To: lsdj@yahoogroups.com\r\n'
             'X-Received: (qmail 4675 invoked from network); 20 Aug 2009 '
             '06:49:25 -0000\r\n'
             'X-Received: from unknown (98.137.34.45)\n'
             '  by m4.grp.sp2.yahoo.com with QMQP; 20 Aug 2009 06:49:25 '
             '-0000\r\n'
             'X-Received: from unknown (HELO mail-ew0-f227.google.com) '
             '(209.85.219.227)\n'
             '  by mta2.grp.sp2.yahoo.com with SMTP; 20 Aug 2009 06:49:24 '
             '-0000\r\n'
             'X-Received: by ewy27 with SMTP id 27so5087139ewy.16\n'
             '        for &lt;lsdj@yahoogroups.com&gt;; Wed, 19 Aug 2009 '
             '23:49:01 -0700 (PDT)\r\n'
             'X-Received: by 10.211.194.4 with SMTP id '
             'w4mr6742951ebp.41.1250750941796;\n'
             '        Wed, 19 Aug 2009 23:49:01 -0700 (PDT)\r\n'
             'Return-Path: &lt;operagasten@...&gt;\r\n'
             'X-Received: from ?192.168.1.2? '
             '(89-253-122-114.customers.ownit.se [89.253.122.114])\n'
             '        by mx.google.com with ESMTPS id '
             '5sm609735eyf.8.2009.08.19.23.49.00\n'
             '        (version=SSLv3 cipher=RC4-MD5);\n'
             '        Wed, 19 Aug 2009 23:49:00 -0700 (PDT)\r\n'
             'To: lsdj@yahoogroups.com\r\n'
             'In-Reply-To: '
             '&lt;dd9445100908192343l5ce1d94bvccc47dbdd0689ea6@...&gt;\r\n'
             'References: '
             '&lt;e1c371f0908170351x6051e48fm135144f40cbeb1e9@...&gt;\n'
             '\t &lt;h6cnbm+sk0k@...&gt;\n'
             '\t &lt;e1c371f0908180053j5afbbb75u4e5ce1bb6fbc344c@...&gt;\n'
             '\t &lt;4A8B17A5.7080709@...&gt; '
             '&lt;001b01ca2110$d16a7a10$743f6e30$@com&gt;\n'
             '\t &lt;700977e10908191847j423573b5o6b1effda41548a47@...&gt;\n'
             '\t &lt;dd9445100908192343l5ce1d94bvccc47dbdd0689ea6@...&gt;\r\n'
             'Content-Type: text/plain\r\n'
             'Date: Thu, 20 Aug 2009 08:48:59 +0200\r\n'
             'Message-Id: &lt;1250750939.4031.0.camel@martin-desktop&gt;\r\n'
             'Mime-Version: 1.0\r\n'
             'X-Mailer: Evolution 2.26.1 \r\n'
             'Content-Transfer-Encoding: 7bit\r\n'
             'X-Originating-IP: 209.85.219.227\r\n'
             'X-eGroups-Msg-Info: 1:12:0:0:0\r\n'
             'From: Martin =?ISO-8859-1?Q?Ahnel=F6v?= '
             '&lt;operagasten@...&gt;\r\n'
             'Subject: Re: [LSDj!] BUGS with 3.9.c\r\n'
             'X-Yahoo-Group-Post: member; u=300939260; '
             'y=SrgefAvU2XVq2eMlgU2WWtb6pkOx4a9cFbinctbTSanFlLjq3Fo\r\n'
             'X-Yahoo-Profile: operagasten\r\n'
             '\r\n'
             'it&#39;s not new, it&#39;s in the demo version even! =)\n'
             '\n'
             'tor 2009-08-20 klockan 02:43 -0400 skrev DDP DDP:\n'
             '&gt; one feature i just discovered, not sure if this is new, is '
             'the tempo TAP\n'
             '&gt; function in the tempo setting.  If you tap B while the '
             'tempo is selected, it\n'
             '&gt; sets the tempo to the tempo you are tapping.  Is that new?  '
             'it screwed me up\n'
             '&gt; a lot while i was setting the tempo.  I would set it to '
             'say, 130, then i\n'
             '&gt; would listen for a bit, click B again to change it again, '
             'and instead of\n'
             '&gt; going up to 131, it would go to 40, becasue of the time '
             'between taps.\n'
             '&gt; \n'
             '&gt; i guess its something new to get used to.\n'
             '&gt; \n'
             '&gt; but i think i&#39;m gonna go back to 3.9.9\n'
             '&gt; \n'
             '&gt; \n'
             '&gt; \n'
             '&gt; On Wed, Aug 19, 2009 at 9:47 PM, Brady Leo '
             '&lt;bradyleo@...&gt; wrote:\n'
             '&gt; \n'
             '&gt; &gt;\n'
             '&gt; &gt;\n'
             '&gt; &gt; Ahhh. This would explain the tremendous trouble I was '
             'having with the WAV\n'
             '&gt; &gt; channel using keyboard sync mode in the latest '
             'version. I also went back to\n'
             '&gt; &gt; 3.9.9 and everything worked fine.\n'
             '&gt; &gt;\n'
             '&gt; &gt; On Wed, Aug 19, 2009 at 5:05 PM, David Dineen-Porter '
             '&lt;theddp@...&lt;theddp%40gmail.com&gt;\n'
             '&gt; &gt; &gt;wrote:\n'
             '&gt; &gt;\n'
             '&gt; &gt;\n'
             '&gt; &gt; &gt; I think I&#39;m uising 3.9.c. whatever the latest '
             'one is, I forget.\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt; But there&#39;s a bug\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt; If you input a note without instrument number, at '
             'least in the wave\n'
             '&gt; &gt; &gt; channel,\n'
             '&gt; &gt; &gt; where I&#39;ve done this, it doesn&#39;t play the '
             'note at that pitch.\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt; Example\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt; C-5 13 -\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt; -- -- P01\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt; E-5 -- --\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt; The note should bend up, and then play at pitch '
             'E-5. Instead, the bend\n'
             '&gt; &gt; &gt; stops, but the pitch E-5 is not played. Resulting '
             'in a flat note. This\n'
             '&gt; &gt; &gt; can\n'
             '&gt; &gt; &gt; be cured by adding the instrument number, '
             'however, this retriggers notw\n'
             '&gt; &gt; &gt; completely, causing the automated table to '
             'advance one step, and the\n'
             '&gt; &gt; &gt; envelope to retrigger, causing a slight click.\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt; This wasn&#39;t the case in 3.9.9, the last LSDJ '
             'I was using.\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt; Just a note.\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt; [Non-text portions of this message have been '
             'removed]\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt; ------------------------------------\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt; Yahoo! Groups Links\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt; &gt;\n'
             '&gt; &gt;\n'
             '&gt; &gt; --\n'
             '&gt; &gt; http://www.dummydrome.com\n'
             '&gt; &gt;\n'
             '&gt; &gt; '
             'o----^v--------^v--------^v--------^v--------^v-----------------------------&gt;\n'
             '&gt; &gt; &quot;If you will it, it is no dream.&quot;\n'
             '&gt; &gt; -Theodor Herzl\n'
             '&gt; &gt;\n'
             '&gt; &gt; [Non-text portions of this message have been removed]\n'
             '&gt; &gt;\n'
             '&gt; &gt;  \n'
             '&gt; &gt;\n'
             '&gt; \n'
             '&gt; \n'
             '&gt; [Non-text portions of this message have been removed]\n'
             '&gt; \n'
             '&gt; \n'
             '&gt; \n'
             '&gt; ------------------------------------\n'
             '&gt; \n'
             '&gt; Yahoo! Groups Links\n'
             '&gt; \n'
             '&gt; \n'
             '&gt; \n'
             '\n'
             '\n',
 'replyTo': 'LIST',
 'senderId': 'wUArcxg73dY2t8Ba5wjw8CmmsXwRpSp4jMUU7_SE3kr4OlJaoFFKPqbnbzdrc_iIDrUFkYQ6gZwqUafpZTY58uBIG7riJjh958rJsZ_TbKzVSe2xDTj1IvCpnaxKei4',
 'spamInfo': {'isSpam': False, 'reason': '12'},
 'specialLinks': [],
 'subject': 'Re: [LSDj!] BUGS with 3.9.c',
 'systemMessage': False,
 'topicId': 10811,
 'userId': 300939260}
Traceback (most recent call last):
  File "yahoo-groups-backup.py", line 129, in <module>
    main()
  File "yahoo-groups-backup.py", line 125, in main
    arguments, cfg_args)
  File "yahoo-groups-backup.py", line 103, in invoke_subcommand
    return module.command(args)
  File "/Users/johank/yahoo-groups-backup/yahoo_groups_backup/subcommands/scrape_messages.py", line 50, in command
    msg = scraper.get_message(cur_message)
  File "/Users/johank/yahoo-groups-backup/yahoo_groups_backup/scraper.py", line 180, in get_message
    return self._massage_message(data)
  File "/Users/johank/yahoo-groups-backup/yahoo_groups_backup/scraper.py", line 130, in _massage_message
    stripped_name, data['authorName'], check_authorname,
AssertionError: Stripped name Martin =?ISO-8859-1?Q?Ahnel=F6v?= didn't match author name Martin Ahnelöv (check name was Martin Ahnelöv)
```

**Comment by jkotlinski** [comment]
Would be nice if this was fixed, since the error prevents me of doing a backup of my group (lsdj). Thanks!

**Comment by csaftoiu** [comment]
@jkotlinski thanks for the report! try it again

**Comment by jkotlinski** [comment]
It works, thanks a lot! :)
