### ISSUE TITLE
Damn, now it's broken

### ISSUE THREAD

**Issue by imfatant** [csaftoiu/yahoo-groups-backup#46]
This was working a month ago (at least, for Chrome). Now it's broken. Damn :(

I just tried both Chrome and Firefox (7th Dec, 2017). No luck. The error is the same for both:

$ ./yahoo-groups-backup.py scrape_messages voicesofnicotinerecovery --driver=chrome --delay=1 --login=covers_tick@yahoo.com --password=hidubcdsync
Detecting the log-in page...
Detecting the log-in page...
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/splinter/element_list.py", line 40, in __getitem__
    return super(ElementList, self).__getitem__(index)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./yahoo-groups-backup.py", line 129, in <module>
    main()
  File "./yahoo-groups-backup.py", line 125, in main
    arguments, cfg_args)
  File "./yahoo-groups-backup.py", line 103, in invoke_subcommand
    return module.command(args)
  File "/home/anthony/yahoo-groups-backup/yahoo_groups_backup/subcommands/scrape_messages.py", line 41, in command
    last_message = scraper.get_last_message_number()
  File "/home/anthony/yahoo-groups-backup/yahoo_groups_backup/scraper.py", line 88, in get_last_message_number
    return self._load_json_url(url)['ygData']['messages'][0]['messageId']
  File "/home/anthony/yahoo-groups-backup/yahoo_groups_backup/scraper.py", line 81, in _load_json_url
    return json.loads(self.br.find_by_tag("pre")[0].text)
  File "/usr/lib/python3.6/site-packages/splinter/element_list.py", line 44, in __getitem__
    self.find_by, self.query))
splinter.exceptions.ElementDoesNotExist: no elements could be found with tag_name "pre"

- Imfatant

**Comment by johnathansult** [comment]
A few years late, but FYI you've posted your email and password here.
