### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed   (unknown error: DevToolsActivePort file doesn't exist)   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

### ISSUE THREAD

**Issue by wizardzen** [csaftoiu/yahoo-groups-backup#58]
Spent hours and just cannot get pass this error. 

> wizardzen@John-PC:~/yahoo-groups-backup$ python3 yahoo-groups-backup.py scrape_messages --driver chrome mustardseedcommunity
Using '--login' from config file
Using '--password' from config file
Traceback (most recent call last):
  File "yahoo-groups-backup.py", line 129, in <module>
    main()
  File "yahoo-groups-backup.py", line 125, in main
    arguments, cfg_args)
  File "yahoo-groups-backup.py", line 103, in invoke_subcommand
    return module.command(args)
  File "/home/wizardzen/yahoo-groups-backup/yahoo_groups_backup/subcommands/scrape_messages.py", line 32, in command
    arguments['--password'])
  File "/home/wizardzen/yahoo-groups-backup/yahoo_groups_backup/scraper.py", line 29, in __init__
    self.br = splinter.Browser(driver)
  File "/home/wizardzen/.local/lib/python3.6/site-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "/home/wizardzen/.local/lib/python3.6/site-packages/splinter/driver/webdriver/chrome.py", line 28, in __init__
    self.driver = Chrome(chrome_options=options, **kwargs)
  File "/home/wizardzen/.local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/wizardzen/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/wizardzen/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/wizardzen/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/wizardzen/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

Exception ignored in: <bound method YahooBackupScraper.__del__ of <yahoo_groups_backup.scraper.YahooBackupScraper object at 0x7fcbd3194e48>>
Traceback (most recent call last):
  File "/home/wizardzen/yahoo-groups-backup/yahoo_groups_backup/scraper.py", line 32, in __del__
    self.br.quit()
AttributeError: 'YahooBackupScraper' object has no attribute 'br'

**Comment by hrenfroe** [comment]
That's an issue with your local Chromedriver installation -- which, unfortunately, I don't know how to fix. I'm fighting with that one myself on a different project. Update if you find out what it is?
